version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000
  db:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      # MYSQL_USER: "apilocaluser"
      # MYSQL_PASSWORD: "uqXSmMj7su"
      MYSQL_DATABASE: "eucalyptus_local"
      TZ: "Asia/Tokyo"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33306:3306
  web:
    image: node:16-alpine
    build:
      context: .
      dockerfile: Dockerfile.web
    command: npm run serve
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - .:/app
volumes:
  mysql_data:
