version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    volumes:
      - .dockervenv:/src/.venv
      - ./api:/src
    ports:
      - 8000:8000
  db:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "eucalyptus_local"
      TZ: "Asia/Tokyo"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33306:3306
  web:
    image: node:16-alpine
    build:
      context: ./web
      dockerfile: Dockerfile.web
    command: npm run dev
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./web:/app
      - node_modules:/app/node_modules
volumes:
  mysql_data:
  node_modules:
