FROM node:16

WORKDIR /app

# Create a temporary directory and copy the package*.json files
WORKDIR /tmp
COPY package*.json ./

# Install the dependencies and move the node_modules directory to /app
RUN npm install && mv node_modules /app/

# Move back to /app
WORKDIR /app

# Copy the rest of the application
COPY . .

# Change the ownership
RUN chown -R node:node /app

# Switch to the node user
USER node

EXPOSE 3000
